name: Test on Self-Hosted Runner

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: ./test.sh
